# -*- coding: utf-8 -*-
"""L11_hmwk_project.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/177DXuNTM2ctZ6vMMZ66YBLwbnuxhBI93
"""

import pandas as pd

df = pd.read_csv('spotify_data clean.csv')
df.head()

df.shape

df.dtypes

df.isnull().sum()

df_clean = df.dropna()

df_clean.describe()

df_clean['album_release_date'].dt.day_name()
display(df_clean[['album_release_date', 'release_year', 'release_day_of_week']].head())

df_clean.to_csv('spotify_data_processed.csv', index=False)
print("Processed data saved to 'spotify_data_processed.csv'")